SEMCR/config/routes.rb
SEMCR::Application.routes.draw do
  resources :ev_comentarios

  resources :est_comentarios

  devise_for :usuarios
  root 'login#login'
  resources :eventos


  resources :establecimientos
  resources :usuarios
  resources :establecimientos do
    post 'agregar_comentario', :on => :member
  end

  resources :establecimientos do
    get 'comentarios', :on => :member
  end
  resources :eventos do
    get 'nuevo_horario', :on => :member
  end

  resources :eventos do
    post 'agregar_horario', :on => :member
  end

  resources :eventos do
    post 'agregar_tipo', :on => :member
  end

  post "login/login"
  get "usuarios/new"
  get "usuarios/show"
  get "login/login"


end

SEMCR/app/views/layouts/_navbar.html.erb
<%= nav_bar :fixed => :top, :brand => "Sistema de Eventos Móvil", :responsive => "true" do %>
    <%= menu_group do %>
        <% if current_usuario %>
            <%= menu_item "Inicio", root_path %>
            <%= menu_divider %>
            <%= drop_down "Establecimientos" do %>
                <%= menu_item "Registrar", new_establecimiento_path %>          
            <% end %>
            <%= drop_down "Eventos" do %>
                <%= menu_item "Registrar", new_evento_path %>          
            <% end %>
        <% end %>
    <% end %>
    <%= menu_group :pull => :right do %>
        <% if current_usuario %>
            <%= menu_item "Cerrar Sesión", destroy_usuario_session_path, method: :delete, :class => "btn btn-default btn-xs"  %>
        <% else %>
            <%= menu_item "Iniciar Sesión", root_path %>
            <%= menu_item "Registro", new_usuario_registration_path%>
        <% end %>
        
    <% end %>
<% end %>

SEMCR/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sistema de Eventos Móvil</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body">
  <%= render :partial => "layouts/navbar" %>
    <div class="container">
      <%= yield %> 

</body>
</html>

SEMCR/app/views/layouts/prueba.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SEMCR" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">SEMCR</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>