SEMCR/config/routes.rb
SEMCR::Application.routes.draw do
  resources :ev_comentarios

  resources :est_comentarios

  devise_for :usuarios
  root 'login#login'
  resources :eventos


  resources :establecimientos
  resources :usuarios
  resources :establecimientos do
    post 'agregar_comentario', :on => :member
  end

  resources :establecimientos do
    get 'comentarios', :on => :member
  end
  resources :eventos do
    get 'nuevo_horario', :on => :member
  end

  resources :eventos do
    post 'agregar_horario', :on => :member
  end

  resources :eventos do
    post 'agregar_tipo', :on => :member
  end

  post "login/login"
  get "usuarios/new"
  get "usuarios/show"
  get "login/login"


end

SEMCR/app/models/evento.rb
class Evento < ActiveRecord::Base
	attr_accessible :nombre, :descripcion, :establecimiento_id, :horario, :ImagenEventos_attributes
	has_many :ImagenEventos, :dependent => :destroy
	accepts_nested_attributes_for :ImagenEventos
	belongs_to :establecimiento
	has_many :EvComentarios, :dependent => :destroy
	has_many :tipos, :dependent => :destroy

end

SEMCR/app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]
  helper :all

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
    respond_to do |format|
      format.json { 
                  if (params[:appkey].eql? appkey)  #si el appkey es correcto
                    evs = @eventos.map { |evento| { :nombre_evento => evento.nombre, :id => evento.id, 
                                                          :descripcion => evento.descripcion, :establecimiento_nombre => evento.establecimiento.nombre,
                                                      :establecimiento_id => evento.establecimiento.id, :tipos => evento.tipos.map {|tipo| {:nombre => tipo.nombre } } } }

                    render json: evs 
                  else
                    render json: {:error => "No autorizado"}
                  end
                  }
      format.html { redirect_to :controller=>'login', :action=>'login' } #solo el app movil puede revisar toda la lista de eventos.
    end
  end

  #GET /eventos/1/nuevo_horario
  # esta accion renderiza el view para poder agregar un nuevo horario al evento
  def nuevo_horario
    @usuario = Evento.find(params[:id]).establecimiento.usuario #busca el usuario al que pertenece el evento
    if (current_usuario != @usuario) #si el usuario logueado no es el mismo
        redirect_to :controller=>'login', :action=>'login' #lo envia a login, no lo deja modificarlo
      end
    #si llega aca, es el dueño del evento
    @evento = Evento.find(params[:id]) #obtener el evento
  end

  # POST /eventos/1/agregar_horario
  def agregar_horario

    #aca se llega mediante la accion anterior, enviando el form de nuevo_horario
  end

  #POST /eventos/1/agregar_tipo
  def agregar_tipo
    @evento = Evento.find(params[:id]) #obtener el evento
    @evento.tipos.create(:nombre => params[:tipo])
    #agregarle el tipo
    redirect_to @evento
   
  end



  # GET /eventos/1
  # GET /eventos/1.json
  def show
    ev = @evento
    respond_to do |format|
      format.html
      format.json { 
                    if (params[:appkey].eql? appkey)  #si el appkey es correcto
                          render :json => {:nombre => ev.nombre, :descripcion => ev.descripcion, :horario => ev.horario, :establecimiento_nombre => ev.establecimiento.nombre,
                                    :establecimiento_id => ev.establecimiento.id, :tipos => ev.tipos.map {|tipo| {:nombre => tipo.nombre } },
                                    :imagenes => ev.ImagenEventos.map { |img| { :url => img.foto.url(:small) }  }  } 
                  else
                    render json: {:error => "No autorizado"}
                  end

                                  }  

    end
  end

  # GET /eventos/new
  def new
    if (usuario_signed_in?) #Si hay un usuario logueado, entonces lo toma
      @usuario = current_usuario
      @evento = Evento.new
      @evento.ImagenEventos.build# crea una imagen por default
    else #Si no hay usuario logueado, entonces no lo deja crear evento y lo manda a loguearse.
      redirect_to :controller=>'login', :action=>'login'
    end

  end

  # GET /eventos/1/edit
  def edit
      @usuario = Evento.find(params[:id]).establecimiento.usuario #busca el usuario al que pertenece el evento
      if (current_usuario != @usuario) #si el usuario logueado no es el mismo
        redirect_to :controller=>'login', :action=>'login' #lo envia a login, no lo deja modificarlo
      end
      @tipos = Tipo.all #obtiene la lista de todos los tipos y la pasa al view
      @evento = Evento.find(params[:id])
      @evento.ImagenEventos.build # crea una imagen por si la desea agregar
      # si llega aca, entonces si es el usuario
  end

  # POST /eventos
  # POST /eventos.json
  def create
    if (usuario_signed_in?) #Si hay un usuario logueado, entonces lo toma
      @evento = Evento.new(evento_params)
    else #Si no hay usuario logueado, entonces no lo deja crear evento y lo manda a loguearse.
      redirect_to :controller=>'login', :action=>'login'
    end
    respond_to do |format|
      if @evento.save
        format.html { redirect_to current_usuario, notice: 'Creado con éxito.'}
        format.json { render action: 'show', status: :created, location: @evento }
      else
        format.html { render action: 'new' }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
      @usuario = Evento.find(params[:id]).establecimiento.usuario #busca el usuario al que pertenece el evento
      if (current_usuario != @usuario) #si el usuario logueado no es el mismo
        redirect_to :controller=>'login', :action=>'login' #lo envia a login, no lo deja modificarlo
      end
      respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to current_usuario, notice: 'Actualizado con éxito' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
      @usuario = Evento.find(params[:id]).establecimiento.usuario #busca el usuario al que pertenece el evento
      if (current_usuario != @usuario) #si el usuario logueado no es el mismo
        redirect_to :controller=>'login', :action=>'login' #lo envia a login, no lo deja modificarlo
      end
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to current_usuario }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit!
    end
end

SEMCR/app/helpers/eventos_helper.rb
module EventosHelper
end

SEMCR/app/views/eventos/_form.html.erb
<%= form_for(@evento) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :establecimiento_id %><br>
    <%= f.number_field :establecimiento_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SEMCR/app/views/eventos/edit.html.erb
    <h1 align="center">Sistema de Eventos Móvil</h1>
    <h3 align="center">Eventos y Organizaciones</h3>
    <p>&nbsp;</p>
    <h2 align="center">Editar Evento</h2>

<%= simple_form_for(@evento, :html=> {:multipart => true}) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div align="center", class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div align="center", class="field">
    <%= f.label 'Descripción' %><br>
    <%= f.text_area :descripcion %>
  </div>

  <% #select para el establecimiento  %>
  <div align="center", class="field">
    <%= f.label :establecimiento_id %><br>
    <%= f.collection_select :establecimiento_id, @usuario.establecimientos, :id, :nombre, prompt: 'Seleccione el establecimiento' %>
  </div>


  <div align="center", class="field">
     <%= f.input :horario,  :as => 'datetime_picker'%>
    <p>&nbsp;</p>
  </div>

<%= f.fields_for :ImagenEventos do |builder| %>

    <% if builder.object.new_record? %>
    <div align="center", class="field">
      <%= builder.label :foto, "Añadir Imagen" %>
      <%= builder.file_field :foto %>
    </div>
    <% end %>

<% end %>  



  <div align="center", class="actions">
    <%= f.submit 'Guardar' %>
  </div>
<% end %>


<%= link_to 'Show', @evento %>
<%= link_to 'Atras', root_path %>

SEMCR/app/views/eventos/index.html.erb
<h1>Listing eventos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Establecimiento</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.nombre %></td>
        <td><%= evento.descripcion %></td>
        <td><%= evento.establecimiento_id %></td>
        <td><%= link_to 'Show', evento %></td>
        <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
        <td><%= link_to 'Destroy', evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evento', new_evento_path %>

SEMCR/app/views/eventos/new.html.erb
<div class="container">
  <div class="content">

    <h1 align="center">Sistema de Eventos Móvil</h1>
    <h3 align="center">Eventos y Organizaciones</h3>
    <p>&nbsp;</p>
    <h2 align="center">Registrar Evento</h2>

<%= simple_form_for(@evento, :html=> {:multipart => true}) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div align="center", class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div align="center", class="field">
    <%= f.label 'Descripción' %><br>
    <%= f.text_area :descripcion %>
  </div>

  <% #select para el establecimiento  %>
  <div align="center", class="field">
    <%= f.label :establecimiento_id %><br>
    <%= f.collection_select :establecimiento_id, @usuario.establecimientos, :id, :nombre, prompt: 'Seleccione el establecimiento' %>
  </div>


  <div align="center", class="field">
     <%= f.input :horario,  :as => 'datetime_picker'%>
    <p>&nbsp;</p>
    
  </div>

<%= f.fields_for :ImagenEventos do |ff| %>

    <% if ff.object.new_record? %>
     <div align="center">

      <%= ff.label :foto, "Seleccione Imagen" %>
      <%= ff.file_field :foto %>
     
      </div>
    <% end %>

<% end %>  

  <div align="center", class="actions">
    <%= f.submit 'Registrar' %>
  </div>
<% end %>

<%= link_to 'Atrás', @usuario %>

</div>
</div>

SEMCR/app/views/eventos/nuevo_horario.html.erb
    <h1 align="center">Sistema de Eventos Móvil</h1>
    <h3 align="center">Eventos y Organizaciones</h3>
    <p>&nbsp;</p>
    <h2 align="center">Registrar Horario</h2>
    <p>&nbsp;</p>
    
<%= simple_form_for @evento, html: {class: 'form-horizontal', align: "center" } do |form| %>
<%= form.input :horario,  :as => 'datetime_picker'%>
<p>&nbsp;</p>
<%= form.button :submit %>

<% end %> 

SEMCR/app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

    <h1 align="center">Sistema de Eventos Móvil</h1>
    <h3 align="center">Eventos y Organizaciones</h3>
    <p>&nbsp;</p>
    <h2 align="center">Evento</h2>
    <p>&nbsp;</p>

<p align="center">
  <strong>Nombre:</strong>
  <%= @evento.nombre %>
</p>

<p align="center">
  <strong>Descripcion:</strong>
  <%= @evento.descripcion %>
</p>

<p align="center">
  <strong>Establecimiento:</strong>
  <%= @evento.establecimiento_id %>
</p>

<p align="center">
  <strong>Horario:</strong>
  <%= @evento.horario %>
</p>
<p align="center">
  <strong>Imágenes del Evento:</strong><br>

<% @evento.ImagenEventos.each do |imagen| %>
      <%= image_tag imagen.foto.url(:medium) %>
<% end %>


<h4 align="center">Etiquetas</h4>

<% if (@evento.tipos.empty?) %>
        <h5 align="center">No tiene etiquetas.</h4>
<% else %>
 
 
        <% @evento.tipos.each do |tipo| %>
         
             <p align="center"><%= tipo.nombre %></p>

          <% end %>
        
      
        </tr>
      </table>
<% end %>



 <p>&nbsp;</p>
 
<h4 align="center">Añadir Tipo/Etiqueta</h4>
<%= form_tag agregar_tipo_evento_path do%>

<p align="center"><%=text_field_tag "tipo"%></p>

<p align="center"><%=submit_tag "Guardar"%></p> 

<% end %>

<% if (usuario_signed_in?) %>
  <%= link_to 'Atrás', current_usuario %>
<%else %>
  <%= link_to 'Atrás', root_path %>
<% end %>  