SEMCR/config/routes.rb
SEMCR::Application.routes.draw do
  resources :ev_comentarios

  resources :est_comentarios

  devise_for :usuarios
  root 'login#login'
  resources :eventos


  resources :establecimientos
  resources :usuarios
  resources :establecimientos do
    post 'agregar_comentario', :on => :member
  end

  resources :establecimientos do
    get 'comentarios', :on => :member
  end
  resources :eventos do
    get 'nuevo_horario', :on => :member
  end

  resources :eventos do
    post 'agregar_horario', :on => :member
  end

  resources :eventos do
    post 'agregar_tipo', :on => :member
  end

  post "login/login"
  get "usuarios/new"
  get "usuarios/show"
  get "login/login"


end

SEMCR/app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 attr_accessible :nombre, :email, :password, :id, :username, :foto, :facebook

 #OJO -> cambiar si se cambia de ambiente 
 Paperclip.options[:command_path] = 'C:\Program Files (x86)\ImageMagick-6.5.6-Q8'
 
 has_many :establecimientos, :dependent => :destroy
 has_many :EstComentarios, :dependent => :destroy
 has_many :EvComentarios, :dependent => :destroy

 has_attached_file :foto, :styles => {:small => "150x150", :medium => "300x300"}, :default_url => "/images/default/missing.PNG"
 validates_attachment :foto, :presence => true
end

SEMCR/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]
	
  #GET /usuarios
  #GET /usuarios.json
  def index
    redirect_to :controller=>'login', :action=>'login' #lo manda a loguearse
  end

  def info
    @establecimiento = Establecimiento.find(params[:id])
    comentarios = @establecimiento.EstComentarios
    coms=comentarios.map { |comentario| { :nombre_usuario => comentario.usuario.nombre, :contenido => comentario.descripcion }}
    render json: coms
  end

  def eventos
    @usuario = Usuario.find(params[:id]) #busca el usuario con ese id
      if (current_usuario != @usuario) #si el usuario logueado no es el mismo
        redirect_to :controller=>'login', :action=>'login'
      end
    @eventos = usuario.establecimientos.eventos
  end



  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
      respond_to do |format| #dependiendo del formato del request, el app movil lo pide por JSON.
      format.html { #si es por HTML, es un browser
        @usuario = Usuario.find(params[:id]) #busca el usuario con ese id
        if (current_usuario != @usuario) #si el usuario logueado no es el mismo
            redirect_to :controller=>'login', :action=>'login' #lo manda a loguearse
        end
        @establecimientos = @usuario.establecimientos
      }
      format.json { #si el request es por JSON
        
                    if (params[:appkey].eql? appkey)  #si el appkey es correcto
                      
                      render json: { :nombre => @usuario.nombre, :id => @usuario.id, :email => @usuario.email, :imagen => @usuario.foto.url(:small) } 
                    else
                             render json: {:error => "No autorizado"}
                    end


      }
      end
  end

  # GET /usuarios/new
  def new
    redirect_to :controller=>'login', :action=>'login' #lo manda a loguearse
  end

  # GET /usuarios/1/edit
  def edit
      @usuario = Usuario.find(params[:id]) #busca el usuario con ese id
      if (current_usuario != @usuario) #si el usuario logueado no es el mismo
        redirect_to :controller=>'login', :action=>'login'
      end
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render action: 'show', status: :created, location: @usuario }
      else
        format.html { render action: 'new' }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id]) #busca el usuario con ese id
      if (current_usuario != @usuario) #si el usuario logueado no es el mismo
        redirect_to :controller=>'login', :action=>'login'
      end
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id]) #busca el usuario con ese id
      if (current_usuario != @usuario) #si el usuario logueado no es el mismo
        redirect_to :controller=>'login', :action=>'login'
      end
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:email, :nombre, :foto, :username, :password, :facebook, :twitter)
    end
end

SEMCR/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

SEMCR/app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.text_field :foto %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SEMCR/app/views/usuarios/_info_usuario.html.erb
<h1 align="center">&nbsp;</h1>

					<p align="center">
					  <%= @usuario.nombre %>
					</p>

			
					<p align="center">
					  <%= image_tag @usuario.foto.url(:medium)%>
					</p>

			
					<p align="center">
					  <strong>Correo Electrónico:</strong>
					  <%= @usuario.email %>
					</p align="center">

		
					<p align="center">
					<%= link_to 'Editar Usuario', edit_usuario_registration_path, :class => "btn btn-default btn-sm"%></p>
					<br>

	

SEMCR/app/views/usuarios/_tabla_establecimientos.html.erb
<h1 align="center">&nbsp;</h1>

			<h4 align="center">Establecimientos Asociados</h4>
	          <p align="center"><%= link_to 'Añadir Establecimiento', new_establecimiento_path, :class => "btn btn-default btn-sm"%></p>

			<% if (@establecimientos.empty?) %>
				<h5 align="center">No tiene establecimientos registrados</h4>
			<% else %>
			<table class="table" width="145">
				<tr>	
						<td width="100"><strong>Nombre</strong></td>
						<td width="15"><%= %></td>
						<td width="15"><%= %></td>
						<td width="15"><%= %></td>
				</tr>
				<% @establecimientos.each do |establecimiento| %>
					  <tr>
						<td width="100"><%= establecimiento.nombre %></td>
						<td width="15"><%= link_to '', establecimiento, :class => "glyphicon glyphicon-eye-open" %></td>
						<td width="15"><%= link_to '', edit_establecimiento_path(establecimiento), :class => "glyphicon glyphicon-tasks" %></td>
						<td width="15"><%= link_to '', establecimiento, :class => "glyphicon glyphicon-trash", method: :delete, data: { confirm: '¿Está segur@?' } %></td>
					  </tr>
					<% end %>				
				</tr>
			</table>
			<% end %>

SEMCR/app/views/usuarios/_tabla_eventos.html.erb
		  <h1 align="center">&nbsp;</h1>
          <h4 align="center">Eventos Registrados</h4>
          <p align="center"><%= link_to 'Añadir Evento', new_evento_path, :class => "btn btn-default btn-sm"%></p>

	  	<% if (@establecimientos.empty?) %>
		<h5 align="center">No tiene eventos registrados</h4>
	  	<% else %>
		  <table cellspacing="20" align="center" class="table">
					<tr>
								<td width="120"><strong>Nombre</strong></td>
								<td width="120"><strong>Descripción</strong></td>
								<td width="150"><strong>Establecimiento</strong></td>
								<td width="100"><%= %></td>
								<td width="100"><%= %></td>
								<td width="100"><%= %></td>
					</tr>
			  <% @establecimientos.each do |establecimiento| %>
				<% @eventos = establecimiento.eventos %>
				<% @eventos.each do |evento| %>
							<tr>
								<td width="120"><%= evento.nombre %></td>
								<td width="120"><%= evento.descripcion %></td>
								<td width="150"><%= evento.establecimiento.nombre %></td>
								<td width="100"><%= link_to '', evento, :class => "glyphicon glyphicon-eye-open" %></td>
								<td width="100"><%= link_to '', edit_evento_path(evento), :class => "glyphicon glyphicon-tasks" %></td>
								<td width="100"><%= link_to '', evento, :class => "glyphicon glyphicon-trash", method: :delete, data: { confirm: '¿Está segur@?' } %></td>
							</tr>
		 
				<% end %>
			  <% end %>

		  </table>
	    <% end %>

SEMCR/app/views/usuarios/edit.html.erb
<div class="container">
  <div class="content">

    <h1 align="center">Sistema de Eventos Móvil</h1>
    <h3 align="center">Eventos y Organizaciones</h3>
    <p>&nbsp;</p>
    <h2 align="center">Editar Usuario</h2>


<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
  <%= devise_error_messages! %>

		  <div align="center"><%= f.label 'Nombre' %><br />
		  <%= f.text_field :nombre, autofocus: true, :class => "form_control" %></div>

		  <div align="center"><%= f.label 'Nombre de Usuario' %><br />
		  <%= f.text_field :username, :class => "form_control"  %></div>

		  <div align="center"><%= f.label 'Correo Electrónico' %><br />
		  <%= f.email_field :email, :class => "form_control"  %></div>

		  <div align="center"><%= f.label 'Imagen' %><br />
		  <%= f.file_field :foto, :class => "form_control"  %></div>

    <p>&nbsp;</p>
		  <div align="center"><%= f.label 'Facebook' %><br />
		  <%= f.text_field :facebook, :class => "form_control"  %></div>
		  <div align="center"><%= f.label 'Twitter' %><br />
		  <%= f.text_field :twitter, :class => "form_control"  %></div>
    <p>&nbsp;</p>

  <div><%= f.label 'Contraseña' %> <i>(déjela en blanco si no quiere cambiarla)</i><br />
    <%= f.password_field :password, autocomplete: "off" %></div>

  <div><%= f.label 'Confirmar contraseña' %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %></div>

  <div><%= f.label 'Contraseña actual' %> <i>(se necesita su contraseña actual para confirmar los cambios)</i><br />
    <%= f.password_field :current_password, autocomplete: "off" %></div>

  <div><%= f.submit "Guardar" %></div>
<% end %>

    <!-- end .content --></div>
  <!-- end .container --></div>

<%= link_to 'Atrás', usuarios_path %>

SEMCR/app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Foto</th>
      <th>Contrasena</th>
      <th>Username</th>
      <th>Facebook</th>
      <th>Twitter</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.foto %></td>
        <td><%= usuario.contrasena %></td>
        <td><%= usuario.username %></td>
        <td><%= usuario.facebook %></td>
        <td><%= usuario.twitter %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

SEMCR/app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

SEMCR/app/views/usuarios/show.html.erb
</head>

<body>

<div class="row">
  <div class="col-md-4">
  		<%= render :partial => "info_usuario" %>


  </div>
  <div class="col-md-8">.
  	
					<%= render :partial => "tabla_establecimientos" %>  
		          	<%= render :partial => "tabla_eventos" %>

  </div>
</div>
   	
 

</body>