SEMCR/config/routes.rb
SEMCR::Application.routes.draw do
  resources :ev_comentarios

  resources :est_comentarios

  devise_for :usuarios
  root 'login#login'
  resources :eventos


  resources :establecimientos
  resources :usuarios
  resources :establecimientos do
    post 'agregar_comentario', :on => :member
  end

  resources :establecimientos do
    get 'comentarios', :on => :member
  end
  resources :eventos do
    get 'nuevo_horario', :on => :member
  end

  resources :eventos do
    post 'agregar_horario', :on => :member
  end

  resources :eventos do
    post 'agregar_tipo', :on => :member
  end

  post "login/login"
  get "usuarios/new"
  get "usuarios/show"
  get "login/login"


end

SEMCR/app/models/establecimiento.rb
class Establecimiento < ActiveRecord::Base
 attr_accessible :id, :nombre, :direccion, :longitud, :latitud, :descripcion, :usuario_id, :foto
 has_many :eventos, :dependent => :destroy
 has_many :EstComentarios
 belongs_to :usuario

 has_attached_file :foto, :styles => {:small => "50x50", :medium => "200x200"}
end

SEMCR/app/controllers/establecimientos_controller.rb
class EstablecimientosController < ApplicationController
  before_action :set_establecimiento, only: [:show, :edit, :update, :destroy]


  def agregar_comentario
    @establecimiento = Establecimiento.find(params[:id])
    @establecimiento.EstComentarios.create(:descripcion => params[:comentario], :usuario_id => current_usuario.id)
    redirect_to @establecimiento
  end

  # GET /establecimientos/1/comentarios.json
  def comentarios
      if (params[:appkey].eql? appkey)  #si el appkey es correcto
        @establecimiento = Establecimiento.find(params[:id])
        comentarios = @establecimiento.EstComentarios
        coms=comentarios.map { |comentario| { :nombre_usuario => comentario.usuario.nombre, :contenido => comentario.descripcion }}
        render json: coms
      else
               render json: {:error => "No autorizado"}
      end
  end

  # GET /establecimientos
  # GET /establecimientos.json
  def index
    @establecimientos = Establecimiento.all
    respond_to do |format|
      format.json {  

                    if (params[:appkey].eql? appkey)  #si el appkey es correcto

                      ests = @establecimientos.map { |establecimiento| { :nombre_establecimiento => establecimiento.nombre, :id => establecimiento.id, 
                                                            :descripcion => establecimiento.descripcion, :longitud => establecimiento.longitud,
                                                            :latitud => establecimiento.latitud, :direccion => establecimiento.direccion, :imagen => establecimiento.foto.url(:small),
                                                            :eventos => establecimiento.eventos.map { |evento| { :nombre => evento.nombre } }      } } 
                      render json: ests
                    else
                             render json: {:error => "No autorizado"}
                    end



                      }
      format.html { redirect_to :controller=>'login', :action=>'login' } #solo el app movil puede revisar toda la lista de establecimientos.
    end
  end

  # GET /establecimientos/1
  # GET /establecimientos/1.json
  def show 
    est = @establecimiento
    respond_to do |format|
      format.html
      format.json { 

                  if (params[:appkey].eql? appkey)  #si el appkey es correcto
                    render :json => {:nombre => @establecimiento.nombre, direccion: @establecimiento.direccion, :latitud => @establecimiento.latitud,
                                     :longitud => @establecimiento.longitud, :descripcion => @establecimiento.descripcion, :imagen => @establecimiento.foto.url(:small),
                                     :comentarios => @establecimiento.EstComentarios.map { |comentario| { :descripcion => comentario.descripcion, :usuario => comentario.usuario.nombre } } }   

                    else
                             render json: {:error => "No autorizado"}
                    end


                                 }
      end
      #No tiene restricciones, queda abierto para el API
  end

  # GET /establecimientos/new
  def new
    if (usuario_signed_in?) #Si hay un usuario logueado, entonces lo toma
      @usuario = current_usuario
      @establecimiento = Establecimiento.new
    else #Si no hay usuario logueado, entonces no lo deja crear establecimiento y lo manda a loguearse.
      redirect_to :controller=>'login', :action=>'login'
    end
  end

  # GET /establecimientos/1/edit
  def edit
      @usuario = Establecimiento.find(params[:id]).usuario #busca el usuario al que pertenece el establecimiento
      if (current_usuario != @usuario) #si el usuario logueado no es el mismo
        redirect_to :controller=>'login', :action=>'login' #lo envia a login, no lo deja modificarlo
      end
      #si llega aca es porque si es el dueño del establecimiento
  end

  # POST /establecimientos
  # POST /establecimientos.json
  def create
    if (usuario_signed_in? != true) #Si no hay usuario logueado
        redirect_to :controller=>'login', :action=>'login' #lo envia a login
    end
    @establecimiento = Establecimiento.new(establecimiento_params)
    @establecimiento.usuario_id = current_usuario.id
    respond_to do |format|
      if @establecimiento.save
        format.html { redirect_to current_usuario, notice: 'Establecimiento was successfully created.' }
        format.json { render action: 'show', status: :created, location: @establecimiento }
      else
        format.html { render action: 'new' }
        format.json { render json: @establecimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /establecimientos/1
  # PATCH/PUT /establecimientos/1.json
  def update
      @usuario = Establecimiento.find(params[:id]).usuario #busca el usuario al que pertenece el establecimiento
      if (current_usuario != @usuario) #si el usuario logueado no es el mismo
        redirect_to :controller=>'login', :action=>'login' #lo envia a login, no lo deja modificarlo
      end
      #si llega aca es porque si es el dueño del establecimiento
    respond_to do |format|
      if @establecimiento.update(establecimiento_params)
        format.html { redirect_to current_usuario, notice: 'Establecimiento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @establecimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /establecimientos/1
  # DELETE /establecimientos/1.json
  def destroy
      @usuario = Establecimiento.find(params[:id]).usuario #busca el usuario al que pertenece el establecimiento
      if (current_usuario != @usuario) #si el usuario logueado no es el mismo
        redirect_to :controller=>'login', :action=>'login' #lo envia a login, no lo deja modificarlo
      end
    @establecimiento.destroy
    respond_to do |format|
      format.html { redirect_to current_usuario }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_establecimiento
      @establecimiento = Establecimiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def establecimiento_params
      params.require(:establecimiento).permit(:nombre, :direccion, :longitud, :latitud, :descripcion, :usuario_id, :foto)
    end
end

SEMCR/app/helpers/establecimientos_helper.rb
module EstablecimientosHelper
end

SEMCR/app/views/establecimientos/_form.html.erb
<%= form_for(@establecimiento) do |f| %>
  <% if @establecimiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@establecimiento.errors.count, "error") %> prohibited this establecimiento from being saved:</h2>

      <ul>
      <% @establecimiento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_area :direccion %>
  </div>
  <div class="field">
    <%= f.label :longitud %><br>
    <%= f.text_field :longitud %>
  </div>
  <div class="field">
    <%= f.label :latitud %><br>
    <%= f.text_field :latitud %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.number_field :usuario_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SEMCR/app/views/establecimientos/edit.html.erb
    <h1 align="center">Sistema de Eventos Móvil</h1>
    <h3 align="center">Eventos y Organizaciones</h3>
    <p>&nbsp;</p>
    <h2 align="center">Editar Establecimiento</h2>

	<%= form_for(@establecimiento) do |f| %>
	  <% if @establecimiento.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@establecimiento.errors.count, "error prohibió", "errores prohibieron") %> que este establecimiento se registrara:</h2>
	      <ul>
	      <% @establecimiento.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <div align="center", class="field">
	    <%= f.label :nombre %><br>
	    <%= f.text_field :nombre %>
	  </div>
	  <div align="center", class="field">
	    <%= f.label "Direccíón" %><br>
	    <%= f.text_area :direccion %>
	  </div>
	  <div align="center", class="field">
	    <%= f.label :longitud %><br>
	    <%= f.text_field :longitud %>
	  </div>
	  <div align="center", class="field">
	    <%= f.label :latitud %><br>
	    <%= f.text_field :latitud %>
	  </div>
	   <p class="help-block" align="center">Puede obtenerlos de Google Maps.</p>
	  <div align="center", class="field">
	    <%= f.label :descripcion %><br>
	    <%= f.text_area :descripcion %>
	  </div>
	  <p>&nbsp;</p>
	  <div align="center", class="field">
	    <%= f.label "Usuario" %><br>
	    <%= label_tag @usuario.nombre%>
	  </div>

	  <div align="center"><%= f.label 'Imagen' %><br />
	      <%= f.file_field :foto, :class => "form_control"  %></div>

	  <div align="center",  class="actions">
	    <%= f.submit 'Guardar'%>
	  </div>
	<% end %>

<%= link_to 'Atrás', current_usuario %>

SEMCR/app/views/establecimientos/index.html.erb
<h1>Listing establecimientos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Longitud</th>
      <th>Latitud</th>
      <th>Descripcion</th>
      <th>Usuario</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @establecimientos.each do |establecimiento| %>
      <tr>
        <td><%= establecimiento.nombre %></td>
        <td><%= establecimiento.direccion %></td>
        <td><%= establecimiento.longitud %></td>
        <td><%= establecimiento.latitud %></td>
        <td><%= establecimiento.descripcion %></td>
        <td><%= establecimiento.usuario_id %></td>
        <td><%= link_to 'Show', establecimiento %></td>
        <td><%= link_to 'Edit', edit_establecimiento_path(establecimiento) %></td>
        <td><%= link_to 'Destroy', establecimiento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Establecimiento', new_establecimiento_path %>

SEMCR/app/views/establecimientos/new.html.erb
<div class="container">
  <div class="content">

    <h1 align="center">Sistema de Eventos Móvil</h1>
    <h3 align="center">Eventos y Organizaciones</h3>
    <p>&nbsp;</p>
    <h2 align="center">Registro de Establecimiento</h2>

<%= form_for(@establecimiento) do |f| %>
  <% if @establecimiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@establecimiento.errors.count, "error prohibió", "errores prohibieron") %> que este establecimiento se registrara:</h2>
      <ul>
      <% @establecimiento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div align="center", class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>

  <div align="center", class="field">
    <%= f.label "Direccíón" %><br>
    <%= f.text_area :direccion %>
  </div>
  <div align="center", class="field">
    <%= f.label :longitud %><br>
    <%= f.text_field :longitud %>
  </div>
  <div align="center", class="field">
    <%= f.label :latitud %><br>
    <%= f.text_field :latitud %>
  </div>
   <p class="help-block" align="center">Puede obtenerlos de Google Maps.</p>
  <div align="center", class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <p>&nbsp;</p>
  <div align="center", class="field">
    <%= f.label "Usuario" %><br>
    <%= label_tag @usuario.email%>
  </div>

  <div align="center"><%= f.label 'Imagen' %><br />
      <%= f.file_field :foto, :class => "form_control"  %></div>

  <div align="center",  class="actions">
    <%= f.submit 'Guardar'%>
  </div>
<% end %>

<%= link_to 'Atrás', @usuario%>

SEMCR/app/views/establecimientos/show.html.erb
<p id="notice"><%= notice %></p>

    <h1 align="center">Sistema de Eventos Móvil</h1>
    <h3 align="center">Eventos y Organizaciones</h3>
    <p>&nbsp;</p>
    <h2 align="center">Establecimiento</h2>

<p align="center">
  <strong>Nombre:</strong>
  <%= @establecimiento.nombre %>
</p>

        <p align="center">
          <%= image_tag @establecimiento.foto.url(:medium)%>
        </p>

<p align="center">
  <strong>Direccion:</strong>
  <%= @establecimiento.direccion %>
</p>

<p align="center">
  <strong>Longitud:</strong>
  <%= @establecimiento.longitud %>
</p>

<p align="center">
  <strong>Latitud:</strong>
  <%= @establecimiento.latitud %>
</p>

<p align="center">
  <strong>Descripcion:</strong>
  <%= @establecimiento.descripcion %>
</p>

<p align="center">
  <strong>Usuario:</strong>
  <%= @establecimiento.usuario.nombre %>
</p>
<p>&nbsp;</p>


<h4 align="center">Comentarios de los Usuarios</h4>

<% if (@establecimiento.EstComentarios.empty?) %>
        <h5 align="center">No tiene comentarios.</h4>
<% else %>
      <table class="table" width="330">
        <tr>  
            <td width="230"><strong>Usuario</strong></td>
            <td width="100"><strong>Contenido</strong></td>
        </tr>
        <% @establecimiento.EstComentarios.each do |estcomentario| %>
            <tr>
            <td width="230"><%= estcomentario.usuario.nombre %></td>
            <td width="100"><%= estcomentario.descripcion %></td>
            </tr>
          <% end %>
        
          
        </tr>
      </table>
<% end %>

<p>&nbsp;</p>


<h4 align="center">Añadir Comentario</h4>
<%= form_tag agregar_comentario_establecimiento_path do%>

<p align="center"><%=text_field_tag "comentario"%></p>

<p align="center"><%=submit_tag "Guardar"%></p> 

<% end %>
<% if (usuario_signed_in?) %>
  <%= link_to 'Atrás', current_usuario %>
<%else %>
  <%= link_to 'Atrás', root_path %>
<% end %>  